name: "Hello World"
description: "Greet someone"
inputs:
  expected:
    description: "expected"
    required: true
outputs:
  actual:
    description: "actual"
    value: ${{ inputs.expected }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 24
