on: [push]

permissions:
  contents: read

jobs:
  main:
    name: A job to say hello
    strategy:
      matrix:
        os: [win32, darwin]
    uses: ./.github/workflows/callup.yml
    with:
      text-to-log: ${{ matrix.os }}
