on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v6
      - id: foo
        uses: ./.github/actions/setup
        with:
          expected: "Mona the Octocat"
      - run: node main.js
        shell: bash
        env:
          ACTUAL: ${{ steps.foo.outputs.actual }}
